<?php
require_once __DIR__ . '/../includes/trip_service.php'; $userId = tp_require_user(); global $auth_db;
$favorites = tp_get_favorites($userId);
$stmt=$auth_db->prepare('SELECT item_type,item_key,title,unit_price,quantity,start_hour,end_hour FROM trip_timetable_items WHERE user_id=? ORDER BY start_hour,id'); $stmt->bind_param('i',$userId);$stmt->execute();$scheduled=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);$stmt->close();
$grouped=['flight'=>[],'hotel'=>[],'restaurant'=>[]];foreach($favorites as $favorite){$grouped[$favorite['item_type']][]=$favorite;}
include __DIR__ . '/../header.php';
?>
<link rel="stylesheet" href="/TravelPal/css/modules/favorites.css?v=1">
<section class="favorites-page"><div class="favorites-shell"><header class="favorites-heading"><div><span>TRIP PLANNER</span><h1>Favorites &amp; timetable</h1><p>Drag a saved favorite into the hour you want to be there. Click a scheduled block to change its finish time.</p></div><a href="/TravelPal/trips/index.php">My Trips <i class="fa-solid fa-arrow-right"></i></a></header>
<div class="planner-layout"><section class="timeline-card" id="printArea"><div class="timeline-card-head"><div><span>Your day</span><h2>Trip timetable</h2></div><button class="clear-timetable no-print" id="clearTimetable">Clear</button></div><div class="timeline"><div class="timeline-hours"><?php for($hour=0;$hour<24;$hour++): ?><div class="timeline-row" data-hour="<?php echo $hour; ?>"><time><?php echo sprintf('%02d:00', $hour); ?></time><div class="timeline-drop" data-hour="<?php echo $hour; ?>"></div></div><?php endfor; ?></div></div><div class="timeline-bottom"><div><span>ESTIMATED TOTAL</span><strong id="estimateRange">RM 0 – 0</strong><small>Based on favorites, passengers and nights.</small></div><button class="print-timetable no-print" onclick="window.print()"><i class="fa-solid fa-print"></i> Print timetable</button></div></section>
<aside class="favorite-list"><div class="favorite-list-head"><span>SAVED ITEMS</span><h2>Drag into your day</h2></div><?php foreach(['flight'=>'Flights','hotel'=>'Hotels','restaurant'=>'Restaurants'] as $type=>$label): ?><section class="favorite-category"><h3><i class="fa-solid fa-<?php echo $type==='flight'?'plane':($type==='hotel'?'hotel':'utensils'); ?>"></i> <?php echo $label; ?></h3><?php if(!$grouped[$type]): ?><p class="no-favorites">No saved <?php echo strtolower($label); ?> yet.</p><?php else: foreach($grouped[$type] as $item): ?><article class="favorite-item" draggable="true" data-favorite='<?php echo tp_h(json_encode(['item_type'=>$item['item_type'],'item_key'=>$item['item_key'],'title'=>$item['title'],'unit_price'=>(float)$item['unit_price'],'quantity'=>max(1,(int)($item['metadata']['guests']??$item['metadata']['nights']??1))])); ?>'><div class="favorite-icon <?php echo tp_h($type); ?>"><i class="fa-solid fa-<?php echo $type==='flight'?'plane':($type==='hotel'?'hotel':'utensils'); ?>"></i></div><div><strong><?php echo tp_h($item['title']); ?></strong><small><?php echo tp_h($item['subtitle']); ?></small><em>RM <?php echo number_format($item['unit_price'],2); ?><?php echo $type==='restaurant'?' est.':' '; ?></em></div><i class="fa-solid fa-grip-lines drag-mark"></i></article><?php endforeach; endif; ?></section><?php endforeach; ?></aside></div></div></section>
<script>
const savedSchedule=<?php echo json_encode($scheduled); ?>, blocks=[], timeline=document.querySelector('.timeline-hours'), estimate=document.getElementById('estimateRange'); let dragging=null;
function timeLabel(h){return String(h).padStart(2,'0')+':00'}
function defaultLength(type){return type==='flight'?8:type==='hotel'?4:1}
function draw(){timeline.querySelectorAll('.scheduled-block').forEach(n=>n.remove());blocks.forEach((item,index)=>{const slot=timeline.querySelector(`.timeline-drop[data-hour="${item.start_hour}"]`);if(!slot)return;const el=document.createElement('button');el.type='button';el.className='scheduled-block '+item.item_type;el.style.height=`calc(${Math.max(1,item.end_hour-item.start_hour)*52}px - 6px)`;el.innerHTML=`<strong>${item.title}</strong><span>${timeLabel(item.start_hour)} – ${timeLabel(item.end_hour)}</span>`;el.title='Click to set the end hour or remove this item';el.onclick=()=>{const answer=prompt(`Finish time for ${item.title} (between ${item.start_hour+1} and 24). Leave blank to remove.`,item.end_hour);if(answer===null)return;if(answer.trim()===''){blocks.splice(index,1)}else{item.end_hour=Math.max(item.start_hour+1,Math.min(24,Number(answer)||item.end_hour));}draw();save();};slot.appendChild(el);});let total=blocks.reduce((sum,item)=>sum+(Number(item.unit_price)||0)*(Number(item.quantity)||1),0);estimate.textContent=`RM ${Math.round(total*.9).toLocaleString()} – ${Math.ceil(total*1.1).toLocaleString()}`}
function save(){fetch('/TravelPal/trips/timetable_action.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save',items:blocks})});}
savedSchedule.forEach(item=>blocks.push({...item,start_hour:Number(item.start_hour),end_hour:Number(item.end_hour),unit_price:Number(item.unit_price),quantity:Number(item.quantity)}));
document.querySelectorAll('.favorite-item').forEach(el=>el.addEventListener('dragstart',()=>{dragging=JSON.parse(el.dataset.favorite);el.classList.add('is-dragging')}));document.querySelectorAll('.favorite-item').forEach(el=>el.addEventListener('dragend',()=>el.classList.remove('is-dragging')));
document.querySelectorAll('.timeline-drop').forEach(drop=>{drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag-over')});drop.addEventListener('dragleave',()=>drop.classList.remove('drag-over'));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag-over');if(!dragging)return;const start=Number(drop.dataset.hour);blocks.push({...dragging,start_hour:start,end_hour:Math.min(24,start+defaultLength(dragging.item_type))});dragging=null;draw();save();});});document.getElementById('clearTimetable').addEventListener('click',()=>{if(confirm('Clear your saved timetable?')){blocks.splice(0);draw();save();}});draw();
</script>
<?php include __DIR__ . '/../footer.php'; ?>
