<?php
require_once __DIR__ . '/../includes/trip_service.php'; $userId = tp_require_user(); global $auth_db;
$orderId = (int)($_GET['order_id'] ?? 0);
$stmt = $auth_db->prepare('SELECT * FROM trip_orders WHERE id = ? AND user_id = ? LIMIT 1'); $stmt->bind_param('ii', $orderId, $userId); $stmt->execute(); $order = $stmt->get_result()->fetch_assoc(); $stmt->close();
if (!$order) { header('Location: /TravelPal/trips/index.php'); exit; }
$stmt = $auth_db->prepare('SELECT * FROM trip_order_items WHERE order_id = ? ORDER BY item_type, id'); $stmt->bind_param('i', $orderId); $stmt->execute(); $items=$stmt->get_result()->fetch_all(MYSQLI_ASSOC); $stmt->close();
include __DIR__ . '/../header.php';
?>
<link rel="stylesheet" href="/TravelPal/css/modules/trips-cart.css?v=1">
<section class="receipt-page"><div class="receipt-actions no-print"><a href="index.php"><i class="fa-solid fa-arrow-left"></i> My Trips</a><button onclick="window.print()"><i class="fa-solid fa-print"></i> Print receipt</button></div><article class="receipt"><header><img src="/TravelPal/logo.png" alt="TravelPal"><div><span>PAYMENT CONFIRMED</span><h1>Travel booking receipt</h1><p><?php echo tp_h($order['order_ref']); ?> · <?php echo date('d M Y, H:i', strtotime($order['created_at'])); ?></p></div></header><div class="receipt-note"><i class="fa-solid fa-circle-check"></i> Show the relevant booking section below at airline check-in or your hotel front desk.</div><?php foreach ($items as $item): $data=json_decode($item['booking_data'] ?: '{}', true) ?: []; ?><section class="ticket"><div class="ticket-type"><i class="fa-solid fa-<?php echo $item['item_type']==='flight'?'plane':'hotel'; ?>"></i> <?php echo strtoupper(tp_h($item['item_type'])); ?></div><div><h2><?php echo tp_h($item['title']); ?></h2><p><?php echo tp_h($item['subtitle']); ?></p><div class="ticket-meta"><span><?php echo $item['item_type']==='flight'?'Passengers':'Nights'; ?>: <strong><?php echo $item['quantity']; ?></strong></span><span>Guests: <strong><?php echo (int)($data['guests'] ?? 1); ?></strong></span><span>Amount: <strong>RM <?php echo number_format($item['unit_price']*$item['quantity'],2); ?></strong></span></div></div><div class="ticket-code">TRAVELPAL<br><strong><?php echo strtoupper(substr(md5($order['order_ref'].$item['id']),0,10)); ?></strong></div></section><?php endforeach; ?><footer><span>Paid (demo)</span><strong>Total paid: RM <?php echo number_format($order['total_amount'],2); ?></strong></footer></article></section>
<?php include __DIR__ . '/../footer.php'; ?>
