<?php
$foodRows = [
    [101, 'Laksa Johor', 'Johor', 'Johor Bahru', 'Noodles', 'RM 8–15', 'Lunch', 'Spaghetti-style noodles served with a thick, aromatic fish gravy, herbs and sambal.', 'https://storage.googleapis.com/images.ikhlas.com/strapi/Laksa_Johor_07b10f6c1a/Laksa_Johor_07b10f6c1a.jpg', 'rich fish gravy and fresh herbs', 'firm spaghetti that holds the thick sauce', 'mix in the sambal gradually and finish with calamansi'],
    [102, 'Kacang Pool', 'Johor', 'Johor Bahru', 'Breakfast', 'RM 7–12', 'Breakfast', 'A savoury broad-bean stew topped with egg, onions and chilli, served with toasted bread.', 'https://dimg04.tripcdn.com/images/0M74e12000pddzhk1E0CA.jpg', 'earthy beans, runny egg and a bright squeeze of lime', 'thick stew against crisp buttered toast', 'tear the toast into small pieces and scoop everything together'],
    [103, 'Mee Bandung Muar', 'Johor', 'Muar', 'Noodles', 'RM 8–14', 'Lunch', 'Yellow noodles in a rich sweet-spicy gravy with egg, prawns and other savoury toppings.', 'https://www.awesomegrasp.com/wp-content/uploads/2022/06/mee-bandung-muar-johor-766x1024.jpeg', 'sweet-spicy prawn gravy with a deep savoury finish', 'springy yellow noodles and tender egg', 'ask for extra lime if you prefer a sharper, less sweet bowl'],
    [201, 'Chicken Rice Balls', 'Melaka', 'Melaka City', 'Rice', 'RM 10–18', 'Lunch', 'Fragrant chicken rice shaped into small balls and served with tender chicken and chilli sauce.', 'https://bagasi.my/images/content/ml-makanan-nasi-ayam.webp', 'fragrant chicken stock, soy and punchy chilli sauce', 'compact soft rice balls with silky poached chicken', 'dip one rice ball at a time so it keeps its shape'],
    [202, 'Nyonya Laksa', 'Melaka', 'Melaka City', 'Noodles', 'RM 8–15', 'Lunch', 'Creamy coconut curry noodles influenced by Peranakan spices and topped with fresh garnishes.', 'https://media.zenfs.com/en/mmail.com.my/8e5efa186c19664378b82b7eb59b3ac6', 'creamy coconut broth layered with warm Peranakan spices', 'soft noodles, bouncy fish cake and juicy prawns', 'stir the chilli in after tasting the broth on its own'],
    [203, 'Kuih Keria', 'Melaka', 'Alor Gajah', 'Dessert', 'RM 3–8', 'Tea time', 'Sweet-potato doughnuts coated with a crisp layer of caramelised palm sugar.', 'https://cdn.yummy.co.id/content-images/images/20200908/nMONyorSwyis3I3n3n7qJWJr5EF8d5zv-31353939353434373036d41d8cd98f00b204e9800998ecf8427e.jpg', 'caramel-like gula Melaka around mellow sweet potato', 'crackly sugar shell and a soft, slightly chewy centre', 'eat it warm while the palm-sugar coating is still crisp'],
    [301, 'Klang Bak Kut Teh', 'Selangor', 'Klang', 'Soup', 'RM 18–35', 'Dinner', 'Pork ribs slowly simmered in a deeply aromatic herbal broth and served with rice and tea.', 'https://images.deliveryhero.io/image/fd-my/products/1438645004.jpg', 'peppery herbal broth with a long savoury aroma', 'fall-apart pork ribs and silky tofu skin', 'order rice and Chinese tea to balance the rich broth'],
    [302, 'Pandan Layer Cake', 'Selangor', 'Klang', 'Dessert', 'RM 8–20', 'Tea time', 'Soft layered sponge cake with a fragrant pandan flavour and light creamy filling.', 'https://images.eatdrinkkl.com/store/postimage/51773/image/webp_version-13b1e97c20abe3ba16ec4138e06a8543.webp', 'gentle pandan fragrance with restrained sweetness', 'soft sponge and cool, smooth pandan layers', 'have it chilled with unsweetened tea or coffee'],
    [303, 'Nasi Ambeng', 'Selangor', 'Shah Alam', 'Rice', 'RM 12–25', 'Lunch', 'A generous Javanese-style rice platter with noodles, vegetables, sambal and seasoned chicken.', 'https://images.deliveryhero.io/image/fd-my/LH/cux6-hero.jpg', 'spiced chicken, sambal and savoury coconut serunding', 'fluffy rice with crisp, tender and saucy side dishes', 'share a large tray and taste the sides in different combinations'],
    [401, 'Ipoh Bean Sprout Chicken', 'Perak', 'Ipoh', 'Chicken', 'RM 15–30', 'Lunch', 'Silky poached chicken served with crunchy local bean sprouts, soy sauce and sesame oil.', 'https://dam.mediacorp.sg/image/upload/s--VMxl3XzZ--/c_fill,g_auto/f_auto,q_auto/v1/8world/images/2023/07/07/20230708_LS_an-ji-chicken_02.JPG', 'clean chicken flavour lifted by soy and sesame oil', 'silky chicken beside exceptionally crunchy bean sprouts', 'order a separate plate of sprouts so they stay crisp'],
    [402, 'Ipoh White Coffee', 'Perak', 'Ipoh', 'Drink', 'RM 3–8', 'Breakfast', 'Smooth, aromatic coffee traditionally roasted and served with condensed or evaporated milk.', 'https://ikanmas.in/wp-content/uploads/2023/07/ipoh-white-coffee.jpg', 'toasty coffee aroma with creamy caramel notes', 'smooth, full-bodied coffee under a light foam', 'request less sweet if you want the roasted flavour to stand out'],
    [403, 'Laksa Kuala Kangsar', 'Perak', 'Kuala Kangsar', 'Noodles', 'RM 7–13', 'Lunch', 'Rice noodles with a light but flavourful fish-based gravy, herbs and a touch of chilli.', 'https://cdn.tasteatlas.com/images/dishes/f4dfe298664b45fc9eb9a928663d5849.jpg?h=684&w=616', 'light fish gravy sharpened by herbs and chilli', 'slippery rice noodles with fresh crunchy garnishes', 'add chilli a little at a time so the delicate fish taste remains'],
    [501, 'Penang Char Koay Teow', 'Penang', 'George Town', 'Noodles', 'RM 8–16', 'Dinner', 'Wok-fried flat rice noodles with prawns, egg, bean sprouts and a smoky savoury finish.', 'https://www.elmundoeats.com/wp-content/uploads/2024/09/Lifting-up-some-Penang-char-kway-teow-using-chopsticks.jpg', 'smoky wok hei, savoury soy and sweet fresh prawns', 'chewy flat noodles with crunchy bean sprouts', 'eat it immediately because the wok aroma fades as it cools'],
    [502, 'Penang Assam Laksa', 'Penang', 'George Town', 'Noodles', 'RM 7–14', 'Lunch', 'Tangy fish-based noodle soup balanced with tamarind, herbs, pineapple and chilli.', 'https://d3avoj45mekucs.cloudfront.net/rojakdaily/media/2nicholas/malaysia/4_55.jpg?ext=.jpg', 'tamarind sourness, flaked fish, mint and a little pineapple sweetness', 'thick rice noodles with crisp shredded vegetables', 'mix the dark prawn paste through the broth for extra depth'],
    [503, 'Mee Udang', 'Penang', 'Butterworth', 'Seafood', 'RM 15–30', 'Dinner', 'Prawn noodles in a sweet and savoury tomato-chilli gravy with fresh seafood toppings.', 'https://cdn.hungryonion.org/original/3X/f/3/f36c3ee0533567de77efa0fe82b86e7abaf005c3.jpeg', 'sweet tomato-chilli gravy infused with prawn shells', 'juicy shell-on prawns and noodles coated in thick gravy', 'squeeze in the lime and keep tissues ready for peeling prawns'],
    [601, 'Mee Calong', 'Pahang', 'Kuantan', 'Noodles', 'RM 7–13', 'Breakfast', 'Simple noodle soup with fish balls, tofu and leafy vegetables in a comforting clear broth.', 'https://ikanmas.in/wp-content/uploads/2022/06/meecalong2.jpg', 'clean fish broth brightened by fried shallots and chives', 'springy handmade fish balls, tofu and soft noodles', 'taste the clear broth before adding the red chilli sauce'],
    [602, 'Patin Tempoyak', 'Pahang', 'Temerloh', 'Fish', 'RM 18–35', 'Lunch', 'River catfish cooked in a rich, spicy and tangy fermented durian gravy.', 'https://resepichenom.com/images/recipes/cmb58jsp40003whzg3hfww08q-1748316085616.jpg', 'tangy fermented durian, turmeric and aromatic river fish', 'tender fatty patin in a thick golden gravy', 'pair it with plenty of plain rice and fresh ulam'],
    [603, 'Puding Diraja', 'Pahang', 'Pekan', 'Dessert', 'RM 8–16', 'Tea time', 'A royal-style dessert with bananas, prunes, cherries and rich custard sauce.', 'https://media.xtra.com.my/2020/05/puding-raja.jpg', 'rich custard balanced by bananas, prunes and cherries', 'creamy sauce with soft fruit and crunchy cashews', 'share one serving after lunch because it is pleasantly rich'],
    [701, 'Hinava', 'Sabah', 'Kota Kinabalu', 'Seafood', 'RM 12–25', 'Lunch', 'Fresh fish cured with lime and mixed with ginger, chilli and local herbs.', 'https://1.bp.blogspot.com/-7FbkIc6mmT0/XYZTsdOZ7WI/AAAAAAAAABA/JTn1sEv3Zt09riJGYiM_0hEy8JvH6Xu8wCLcBGAsYHQ/s1600/Hinava.jpg', 'bright lime, fresh fish, ginger and a clean chilli kick', 'firm cured fish with crisp sliced aromatics', 'choose a busy local place where the fish is prepared very fresh'],
    [702, 'Sabah Grilled Seafood', 'Sabah', 'Kota Kinabalu', 'Seafood', 'RM 25–60', 'Dinner', 'Fresh local fish, prawns or squid grilled and served with spicy dipping sauces.', 'https://tempatcuti.my/wp-content/uploads/2023/12/seafood-sinsuran-night-market-1024x687.jpg', 'charred seafood sweetness with spicy, citrusy dipping sauce', 'smoky fish, snappy prawns and tender squid', 'confirm the price and weight before the seafood goes on the grill'],
    [703, 'UFO Tart', 'Sabah', 'Sandakan', 'Dessert', 'RM 3–8', 'Tea time', 'A soft round cake topped with custard and a light swirl of meringue.', 'https://ik.imagekit.io/tvlk/blog/2018/07/UFO-Tarts.jpg?tr=dpr-2,w-675', 'buttery cake, eggy custard and lightly sweet meringue', 'soft base with silky custard and an airy top', 'buy a freshly baked tart and enjoy it with local coffee'],
    [801, 'Sarawak Laksa', 'Sarawak', 'Kuching', 'Noodles', 'RM 8–16', 'Breakfast', 'Rice vermicelli in a fragrant spiced coconut broth with chicken, prawns and egg.', 'https://i.natgeofe.com/n/00a5bfb1-71ea-4576-802b-15fd92de5302/kuch_cul_laksa_52A1949.jpg', 'peppery spice paste, coconut and savoury prawn broth', 'fine vermicelli with shredded chicken, egg and prawns', 'squeeze in the lime and add sambal halfway through the bowl'],
    [802, 'Kolo Mee', 'Sarawak', 'Kuching', 'Noodles', 'RM 6–12', 'Breakfast', 'Springy dry noodles tossed in a light savoury sauce and topped with sliced meat.', 'https://static.wixstatic.com/media/4b5db5_68c2c053cb8b4633b54009df7188a8b8~mv2.jpg/v1/fill/w_500,h_500,al_c,q_80/4b5db5_68c2c053cb8b4633b54009df7188a8b8~mv2.jpg', 'light savoury dressing, char siu and fragrant shallot oil', 'dry, springy noodles with crisp pork bits', 'toss the noodles thoroughly before adding pickled chilli'],
    [803, 'Nuba Laya', 'Sarawak', 'Miri', 'Rice', 'RM 10–20', 'Lunch', 'Soft mashed rice traditionally enjoyed with flavourful meat, vegetables or soup.', '/TravelPal/restaurant/images/generated/nuba-laya.jpg', 'gentle rice aroma that lets the accompanying dishes shine', 'smooth, sticky rice with a comforting porridge-like body', 'eat it with a strongly flavoured meat or fermented fish side'],
];

$foodOptions = array_map(static function (array $row): array {
    return [
        'id' => $row[0], 'name' => $row[1], 'state' => $row[2], 'city' => $row[3],
        'category' => $row[4], 'price' => $row[5], 'best_time' => $row[6],
        'description' => $row[7], 'image' => $row[8],
        'review_notes' => ['flavour' => $row[9], 'texture' => $row[10], 'tip' => $row[11]],
    ];
}, $foodRows);

$foodAreas = [
    'Johor Bahru' => ['Johor Bahru Heritage Food Area', 'Jalan Tan Hiok Nee, Bandar Johor Bahru, 80000 Johor Bahru, Johor', ['https://leveragehotel.com/cdn/shop/articles/let-s-eat-at-old-street.jpg?v=1704725298', '/TravelPal/restaurant/images/generated/sultan-abu-bakar-mosque.jpg'], ['Jalan Tan Hiok Nee heritage street', 'Sultan Abu Bakar State Mosque']],
    'Muar' => ['Muar Glutton Street Food Area', 'Jalan Haji Abu, 84000 Muar, Johor', ['https://3.bp.blogspot.com/-nU3rEFNY-BQ/VwZIF_Mba_I/AAAAAAACY1U/iTxgYSEfd0g7ZupZglLLMGTHc2I5Wd9iw/s1600/DSC03579.JPG', 'https://nickchan.net/wp-content/uploads/2014/02/8298115937_202760575d_z.jpg'], ['Muar Glutton Street market', 'Jalan Haji Abu food street']],
    'Melaka City' => ['Jonker Walk Food Area', 'Jalan Hang Jebat, 75200 Melaka, Melaka', ['https://ak-d.tripcdn.com/images/1mj3v12000d0c9wnzC78F.jpg', 'https://www.holidaygogogo.com/wp-content/wpmowebp/wp-content/uploads/2012/09/Melaka.webp'], ['Jonker Walk entrance', 'Melaka Dutch Square']],
    'Alor Gajah' => ['Alor Gajah Town Food Area', 'Alor Gajah Town Centre, 78000 Alor Gajah, Melaka', ['https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Alor_Gajah_Square.JPG/960px-Alor_Gajah_Square.JPG.webp', 'https://www.holidaygogogo.com/wp-content/wpmowebp/wp-content/uploads/2012/09/Melaka.webp'], ['Alor Gajah Square', 'Melaka Dutch Square']],
    'Klang' => ['Klang Town Food Area', 'Bandar Klang, 41000 Klang, Selangor', ['https://selangor.travel/wp-content/uploads/2017/04/Galeri_Diraja_Sultan_Abdul_Aziz.jpg', '/TravelPal/restaurant/images/generated/istana-alam-shah.jpg'], ['Royal Gallery Sultan Abdul Aziz', 'Istana Alam Shah']],
    'Shah Alam' => ['Shah Alam Food Area', 'Seksyen 7, 40000 Shah Alam, Selangor', ['https://www.encirclephotos.com/wp-content/uploads/Malaysia-Shah-Alam-Blue-Mosque-Shaw-s-Vision-1080x1440.jpg', 'https://selangor.travel/wp-content/uploads/2017/04/Galeri_Diraja_Sultan_Abdul_Aziz.jpg'], ['Sultan Salahuddin Abdul Aziz Shah Mosque', 'Selangor Royal Gallery']],
    'Ipoh' => ['Ipoh Old Town Food Area', 'Ipoh Old Town, 30000 Ipoh, Perak', ['https://cdn.motherhood.com.my/wp-content/uploads/sites/2/2022/02/07141553/tempat-menarik-di-Ipoh.jpg', '/TravelPal/restaurant/images/generated/ipoh-railway-station.jpg'], ['Ipoh heritage lane', 'Ipoh Railway Station']],
    'Kuala Kangsar' => ['Kuala Kangsar Town Food Area', 'Kuala Kangsar Town Centre, 33000 Kuala Kangsar, Perak', ['/TravelPal/restaurant/images/generated/ubudiah-mosque.jpg', 'https://cdn.motherhood.com.my/wp-content/uploads/sites/2/2022/02/07141553/tempat-menarik-di-Ipoh.jpg'], ['Ubudiah Mosque', 'Perak heritage lane']],
    'George Town' => ['George Town Heritage Food Area', 'Lebuh Chulia, 10200 George Town, Penang', ['https://www.wanderluluu.com/wp-content/uploads/2017/12/IMG_2120.jpg', 'https://www.reisen-und-blog.de/wp-content/uploads/malaysia-pulau-pinang-georgetown-sehenswuerdigkeiten-chew-jetty-1024x578.jpg'], ['George Town street art', 'Chew Jetty boardwalk']],
    'Butterworth' => ['Butterworth Food Area', 'Butterworth Town Centre, 12000 Butterworth, Penang', ['/TravelPal/restaurant/images/generated/butterworth-ferry.jpg', 'https://upload.wikimedia.org/wikipedia/commons/e/e2/Skyline_of_Butterworth_in_Seberang_Perai_2025.jpg'], ['Butterworth ferry terminal', 'Butterworth skyline']],
    'Kuantan' => ['Kuantan Town Food Area', 'Jalan Besar, 25000 Kuantan, Pahang', ['https://malaysiaholiday.com.my/ms/listing/wordpress/wp-content/uploads/2023/10/mosque-in-pahang.jpg', '/TravelPal/restaurant/images/generated/temerloh-riverside.jpg'], ['Sultan Ahmad Shah Mosque', 'Pahang riverside']],
    'Temerloh' => ['Temerloh Riverside Food Area', 'Temerloh Town Centre, 28000 Temerloh, Pahang', ['https://pahangtourism.org.my/destination/must-visit-places-in-pahang/item/img?format=raw&h=400&id=48%3Ahanging-bridge&w=600', '/TravelPal/restaurant/images/generated/temerloh-riverside.jpg'], ['Temerloh hanging bridge', 'Temerloh riverside']],
    'Pekan' => ['Pekan Royal Town Food Area', 'Pekan Town Centre, 26600 Pekan, Pahang', ['https://malaysiaholiday.com.my/ms/listing/wordpress/wp-content/uploads/2023/10/mosque-in-pahang.jpg', '/TravelPal/restaurant/images/generated/temerloh-riverside.jpg'], ['Pahang royal-town architecture', 'Pahang River landmark']],
    'Kota Kinabalu' => ['Gaya Street Food Area', 'Gaya Street, 88000 Kota Kinabalu, Sabah', ['https://www.touropia.com/gfx/b/2019/11/kota_kinabalu_city_mosque.jpg', '/TravelPal/restaurant/images/generated/gaya-street-market.jpg'], ['Kota Kinabalu City Mosque', 'Gaya Street evening market']],
    'Sandakan' => ['Sandakan Town Food Area', 'Sandakan Town Centre, 90000 Sandakan, Sabah', ['https://bagasi.my/images/content/percuma-sdk-sim-sim.webp', 'https://www.touropia.com/gfx/b/2019/11/kota_kinabalu_city_mosque.jpg'], ['Sim Sim Water Village', 'Sabah coastal landmark']],
    'Kuching' => ['Kuching Heritage Food Area', 'Carpenter Street, 93000 Kuching, Sarawak', ['https://media.edgeprop.my/s3fs-public/editorial/my/2023/July/10/Sarawaktourismboard.jpg', 'https://i.pinimg.com/originals/fd/d5/7b/fdd57b30a2b046395911bc64dc68bead.jpg'], ['Darul Hana Bridge and Sarawak River', 'Kuching Waterfront']],
    'Miri' => ['Miri City Food Area', 'Miri City Centre, 98000 Miri, Sarawak', ['https://ak-d.tripcdn.com/images/1i63e223488m78skwBCEE.jpg?proc=source%2Ftrip', 'https://media.edgeprop.my/s3fs-public/editorial/my/2023/July/10/Sarawaktourismboard.jpg'], ['The Grand Old Lady at Canada Hill', 'Sarawak riverside landmark']],
];

$foodAreas = array_map(static function (array $area): array {
    return ['name' => $area[0], 'address' => $area[1], 'images' => $area[2], 'photo_labels' => $area[3]];
}, $foodAreas);
